#! /bin/sh
/usr/lib/polkit-kde-authentication-agent-1 &
/home/ana/.config/polybar/launch.sh &
picom --experimental-backends --xrender-sync-fence &
ckb-next -b &
sleep 7s &
sxhkd &

bspc monitor -d o n e s h o t n i k o

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty border=off
bspc rule -a Steam state=floating follow=on

feh --bg-fill /home/ana/oneshot.png
